In [59]:
import numpy as np
x = np.array([(1,3,4,2,9,6,5)])

In [60]:
x = x.transpose()


In [61]:
index = x.argsort(axis=0)[::-1]
index 

array([[4],
       [5],
       [6],
       [2],
       [1],
       [3],
       [0]])

In [62]:
index

array([[4],
       [5],
       [6],
       [2],
       [1],
       [3],
       [0]])

In [64]:
index[0]

array([4])